# Generated by Django 4.2 on 2023-06-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
